os: Visual Studio 2015

configuration: Release
cache: C:\Users\appveyor\.dnx\packages

nuget:
  disable_publish_on_pr: true

build_script:
- ps: .\build.ps1

artifacts:
- path: artifacts\packages\**\*.nupkg
  name: MyGet